#pragma once

#if 0

// ../_RNLib/
#include "../_RNLib/RNmain.h"
#include "../_RNLib/Basis/3DObject/Body/doll3D.h"
#include "../_RNLib/Basis/3DObject/Body/doll3D-manager.h"
#include "../_RNLib/Basis/3DObject/Body/motion3D.h"
#include "../_RNLib/Basis/3DObject/Body/setup3D.h"
#include "../_RNLib/Basis/Calculation/ease.h"
#include "../_RNLib/Basis/Calculation/geometry.h"
#include "../_RNLib/Basis/Calculation/hit-test.h"
#include "../_RNLib/Basis/Calculation/matrix.h"
#include "../_RNLib/Basis/Calculation/number.h"
#include "../_RNLib/Basis/Draw/PutObject/model.h"
#include "../_RNLib/Basis/Draw/PutObject/polygon2D.h"
#include "../_RNLib/Basis/Draw/PutObject/polygon3D.h"
#include "../_RNLib/Basis/Draw/PutObject/text2D.h"
#include "../_RNLib/Basis/Draw/PutObject/text3D.h"
#include "../_RNLib/Basis/Draw/camera.h"
#include "../_RNLib/Basis/Draw/camera-manager.h"
#include "../_RNLib/Basis/Draw/color.h"
#include "../_RNLib/Basis/Draw/draw-manager.h"
#include "../_RNLib/Basis/Draw/draw-state.h"
//#include "../_RNLib/Basis/Draw/light3D.h"
#include "../_RNLib/Basis/Draw/regist-info.h"
#include "../_RNLib/Basis/Draw/text.h"
#include "../_RNLib/Basis/Draw/texture.h"
#include "../_RNLib/Basis/Mechanical/count.h"
#include "../_RNLib/Basis/Mechanical/file.h"
#include "../_RNLib/Basis/Mechanical/input.h"
#include "../_RNLib/Basis/Mechanical/memory.h"
#include "../_RNLib/Basis/Mechanical/object.h"
#include "../_RNLib/Basis/Mechanical/object-manager.h"
#include "../_RNLib/Basis/Mechanical/regist.h"
#include "../_RNLib/Basis/Mechanical/sound.h"
#include "../_RNLib/Basis/Mechanical/window.h"
#include "../_RNLib/Basis/default-data.h"
#include "../_RNLib/Basis/options.h"

#endif